### ISSUE TITLE
QS v3.0 breaks the Qlik style.

### ISSUE THREAD

**Issue by MrKotecha** [erikwett/qsVariable#4]
The extension appears to be broken by the upgrade to 3.0.

**Comment by erikwett** [comment]
Try downloading the latest version, where this is fixed.

**Comment by MrKotecha** [comment]
Thanks Erik - we've downloaded the latest QS build and extension. The Qlik style does not seem to be being applied? i.e. the buttons don't look as they normally do and you cannot see which option is selected.
![qsvariable-3 0-broken](https://cloud.githubusercontent.com/assets/20300300/16613644/0a0569b0-4365-11e6-97d2-50f8011cedcb.PNG)

**Comment by erikwett** [comment]
I apologize, you are right. I made a mistake when I updated this. Should be OK now, please try again.

**Comment by MrKotecha** [comment]
Thanks Erik, I’ll ask the team to test and come back to you if there are any issues.

Kind regards,

Chirag

Chirag Kotecha
Advisor, Management Consulting
Technology Enablement

T: +44 (0)207 311 2589
M: +44 (0)7766 247 933

**Comment by paulyeo11** [comment]
Hi Erik

I am facing the same issue .

I am also using ver 3 QS .

I have try to re-install the latest extension , still the same , may i know where i go wrong ?

Paul

**Comment by paulyeo11** [comment]
Hi chirag

I am still facing the same issue , even I re install var extension twice

In case you have solve the issue 

Pls info me

Paul
